### ISSUE TITLE
structure of precompute_DS

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#10]
I find the structure of precompute_DS confusing, right now we do:

precompute_DS => compute_DS => delta_sigma_catalog => delta_sigma_single => get_per_pair_results 

But do we need all of these? For example, I think the first three could be merged into one? I find myself spending a lot of time trying to figure out what is done where when the number of steps in the computation isn't that large ...

**Comment by dr-guangtou** [comment]
@alexieleauthaud @Christopher-Bradshaw 

I think this is just considered a standard (or even recommended) approach for Python now.  Each function should do one and only one thing.  

`precompute_DS` is a script for users, and it should look as simple as possible.  So I think it is good practice to separate the actual `delta_sigma_catalog` function in the `lib`. 

That said, I do think the first two steps can be merged.  

1) the `computeDS` function in `precompute_DS` script can be easily absorbed by the `main()` function.  
2) we already have a `computeDS.py` script, it is better to make sure class, function, script names are unique.

**Comment by Christopher-Bradshaw** [comment]
More than just python, that it generally considered good practice in all programming languages. Exactly as song says, each function should do just one thing. Having functions that handle different levels of abstraction is often a nice way to do this - f1 builds delta sigma for a single lens source pair f2 combines all sources for a single lens to build ds for a single lens f3 combines ds for all the lenses to do it for the catalog f4 saves that to file. At least that is how I think about it.

Ideally this should make it easier to understand what is being done where. If this isn't the case an issue might be naming? Despite having written those it took me a second to remember what `get_per_pair_results` was. `delta_sigma_single_pair` might be better there and `delta_sigma_single_lens` might be better for `delta_sigma_single`.

I strongly agree with song's second point. having the computeDS function and script is bad. I should have converted that when we renamed this script to precompute.
Removing one of the layers of `computeDS`/`main` is probably OK too, those are pretty small.

**Comment by dr-guangtou** [comment]
This is dealt with in commit:  https://github.com/alexieleauthaud/DeltaSigmaPipelineHSC/pull/28/commits/24935739e2b95b55e45efcf02e2a68eb9090e4a2

Now we only have one `main` function in the `runPrecomputeDS` script.  

I will close it.
