### ISSUE TITLE
for chris

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#11]
For chris: this needs to be cleaned up... in delta_sigma.py

    # cbx understand this and add comment
    per_pair_results['inverse_sigma_crit'] = (1.0 / sigma_crit(
        np.full(len(sources[ds.sf['z']]), lens['z']), # should change this
        sources[ds.sf['z']]))

**Comment by dr-guangtou** [comment]
This has already been addressed, will close
