### ISSUE TITLE
Structure of delta_sigma

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#12]
Is there any reason get_per_pair_results and group_results_in_radial_bins need to be separate functions
? It would make more sense for me to have these as one function ... basically the heart of the computation ...it would make the code easier to read, since this is where most bugs are likely to creep in ...

**Comment by dr-guangtou** [comment]
This is addressed in commit:  https://github.com/alexieleauthaud/DeltaSigmaPipelineHSC/pull/28/commits/9d7c103311b080703204bb11eaad4ce88e36cda5 

We merge the two functions mentioned above into a single `core_delta_sigma_function`, and also adjust the `delta_sigma_single` function accordingly. 

Will close it.
