### ISSUE TITLE
jack-knife

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#13]
I don't think we need to carry around jk any more in group_results_in_radial_bins .....

**Comment by dr-guangtou** [comment]
This is dealt with in commit: https://github.com/alexieleauthaud/DeltaSigmaPipelineHSC/pull/28/commits/a64f12b2cd9a175a86edaee4c5ad37ba9efbd601 

I will close it.
