### ISSUE TITLE
Shape noise errors 

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#15]
Check this in delta_sigma.py 

       # We keep track of these for shape noise errors
        # ALEXIE: check, use e-weight here? Check against Melanie's code
        r['ds_t_sq'] = np.sum(pprib['e_t'] ** 2 * pprib['e_weight'])
        r['ds_x_sq'] = np.sum(pprib['e_x'] ** 2 * pprib['e_weight']

**Comment by dr-guangtou** [comment]
This part is based on: https://github.com/msimet/GGLensing/blob/master/deltasigma.py

```
try:
     if 'e1' in names:
         tg1 = sourcedata['e1'][m2]/ggc.responsivity
         tg2 = sourcedata['e2'][m2]/ggc.responsivity
     elif 'g1' in names:
         tg1 = sourcedata['g1'][m2]
         tg2 = sourcedata['g2'][m2]
```

So here, the `tg1`, `tg2` are our `e1`, `e2` with `responsivity` applied. 

```
# Project e1 and e2 into the proper reference frame, including 
# SDSS e1 sign flip if necessary 
gtan = -ggc.e1_sign*tg1*cos2phi - tg2*sin2phi
gcross = ggc.e1_sign*tg1*sin2phii - tg2*cos2phi
```

`gtan`, `gcross` are the projected tangential, cross shear term. 

```
gtanweight = numpy.copy(weight)
gcrossweight = numpy.copy(weight)
gtanweight *= sigmacritinverse*sigmacritinverse
gcrossweight *= sigmacritinverse*sigmacritinverse
```

`gtanweight`, `gcrossweight` include the square of inverse of `sigma_crit`. 

```
dstsq[j,i] = numpy.sum(gtan[mask] ** 2 * gtanweight[mask] *
                                       sigmacritinverse[mask] ** 2)
dsxsq[j,i] = numpy.sum(gcross[mask] ** 2 * gcrossweight[mask] *
                                        sigmacritinverse[mask] ** 2)
dstsq_stable[j,i] = numpy.sum(gtan[mask] ** 2 * weight[mask]) 
dsxsq_stable[j,i] = numpy.sum(gcross[mask] ** 2 * weight[mask]) 
```

If the `ds_t_sq` and `ds_x_sq` terms refer to the `_stable` version, the current equations are correct.

**Comment by dr-guangtou** [comment]
This issue will be closed, the explanation is copied to a newer one.
