### ISSUE TITLE
naming conventions in computeDS

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#16]
be careful with "shear" and "DS" in computeDS

rename
calculate_shear
to 
calculate_DS
or something like that ...

**Comment by dr-guangtou** [comment]
For function, method, and variables, I suggest we avoid capital letter.  This is what @Christopher-Bradshaw is doing now I think.  

so should be `calculate_dsigma` or `calculate_delta_sigma` sounds better to me.  

This is what I learn from `halotools` that long, descriptive function name is actually good practice.

**Comment by Christopher-Bradshaw** [comment]
Good point @alexieleauthaud important distinction. 
Also I'm a big fan of having some style guide as song suggests. No real preference as to what it is but big fan of being consistant with it. I'm happy with `long_snake_case`.

I'll make a PR sometime to address the shear/DS distinction and another to do something about style later today/this weekend. Will scratch my OCD itch :)

**Comment by alexieleauthaud** [comment]
Yes, happy to go with these suggestions. Right now, we just have too many functions named similar things to "compute_delta_sigma" and not all of the things called this way, actually compute ds. Chris, shall we plan to discuss some of these points in person?

**Comment by dr-guangtou** [comment]
We made a few changes in commit:  https://github.com/alexieleauthaud/DeltaSigmaPipelineHSC/pull/28/commits/f6ebcdc41e6936443d1bc837391c2c8b569f9c23 

But apparently, we need more fundamental changes to this script, so will deal with them later.  

I will create a separate issue, and close this one
