### ISSUE TITLE
Check m and R and jack-knife

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#18]
check if m and R should be in or out of the jack knife calculation

**Comment by dr-guangtou** [comment]
@alexieleauthaud What's the recommendation here.  

Right now it is within the jackknife calculation.

**Comment by alexieleauthaud** [comment]
Yes, let's keep it in the jack-knife calculation. That is to say, K and R get re-computed every time a jack-knife region is removed.

**Comment by dr-guangtou** [comment]
Ok, in that case, I will close this issue.  

In the new issue for `computeDS`, I still mention this issue, so we can keep the discussion there.
