### ISSUE TITLE
change the name of R

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#20]
To be consistent with the notation in the PDF, can we please change this
sum_den_r-1
to 
sum_den_r

**Comment by dr-guangtou** [comment]
In `lib/precompute_ds.py` and `runComputeDS.py`, change: 

* `sum_num_r-1` to `sum_num_r`
* `sum_den_r-1` to `sum_den_r`

Will close the issue.
