### ISSUE TITLE
change name of m

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#21]
in computeDS 

change the name of the summed quantity to K to be consistent with the PDF document that I added

combined['m'] = np.sum(bins['sum_num_m'], axis=0) / np.sum(bins['sum_den'], axis=0)

to 

combined['K']

**Comment by dr-guangtou** [comment]
In `lib/precompute_ds.py` and `runComputeDS.py`, change: 

* `sum_num_m` to `sum_num_k`
* `sum_den_m` to `sum_den_k`
* `combined['m']` to `combined['k']`
