### ISSUE TITLE
add to readme file

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#23]
in the readme file: ./precomputeDS.py <CONFIG_FILE> [-p parallization]
what does parallelization mean? Number or cores to run it on?
does it matter if this number is a power of 2 for efficiency (this is the case for swot)?

I added this in the readme, I think this is true, please check!
Assumed coordinate from is (X,Y) = (ra,dec)

**Comment by dr-guangtou** [comment]
Add explanation of `p` in Readme.  

Close this issue.
