### ISSUE TITLE
print progress

### ISSUE THREAD

**Issue by joshspeagle** [alexieleauthaud/DeltaSigmaPipelineHSC#44]
Would be great to have when running `runPrecomputeDS.py` on the lens and random catalogs.

**Comment by dr-guangtou** [comment]
This could be a nice feature for the long pre-compute step.  It also relates to what's the best way to run the pre-compute in parallel.  

After discussion with Josh, we think there are a few issues:
1. Right now, we actually have a for loop for all the fields, which is not ncessarily the most efficient way.
2. The `source_field` is passed using global variable...I guess it depends on person, but it would not be my first choice.  

This requires more speed tests, but we could just separte the lens catalogs into a series of chunks and require the objects in each chunk has to belong to a single field.  We could simply output something lie "10/15 chunks are done!" as progress bar.
