### ISSUE TITLE
photoz flags

### ISSUE THREAD

**Issue by alexieleauthaud** [alexieleauthaud/DeltaSigmaPipelineHSC#9]
we need to distinguish between 2 different photoz quality cuts: global cuts versus lens source separation cuts. Josh will be visiting from the 18th for a week and we will implement those then. But in the meantime, can we add an option in the config files for this?

Right now, global quality cuts are set to happen in precomputeDS

lens-source separation cuts are set to happen in delta_sigma.py

Can someone please add an option on the config files for "global_photoz_cuts" to be used in precomputeDS?

Josh and I will work together to add various options there.

**Comment by dr-guangtou** [comment]
This is partially dealt with in commit: https://github.com/alexieleauthaud/DeltaSigmaPipelineHSC/pull/28/commits/38ce3390478515281c519a7d478eb7b533d0dd06 

We add placeholders in the `config.py` and all example configuration files.
